services:
  # ------------------- USER DB -------------------
  db:
    image: postgres:16
    container_name: blog_user_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432" # maps host port 5433 → container 5432
    volumes:
      - user_dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ------------------- REDIS -------------------
  redis:
    image: redis:8
    container_name: blog_user_redis
    restart: always
    ports:
      - "6382:6379" # maps host port 6382 → container 6379
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  user_dbdata:
